#!/usr/bin/env python3
import sys,json,csv,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from trgr.evaluation_protocol_audit import *
pred=(ROOT/'checkpoints/baseline/scene_01/mesh/tsdf_fusion_post_30000.ply').resolve();gt=(ROOT/'data/translab/scene_01/meshes/scene_mesh.obj').resolve();meshdir=pred.parent;out=ROOT/'outputs/scene_01/protocol_audit';out.mkdir(parents=True,exist_ok=True)
official=json.loads((ROOT/'reports/stage0_baseline_parity.json').read_text())['geometry_metrics'];rep,ppts,gpts=reproduce_from_official_intermediate(meshdir/'vis_scene_01_data_down_stl.ply')
errs={'f1_abs':abs(rep['f1_score']-official['f1_score']),'precision_abs':abs(rep['precision']-official['precision']),'recall_abs':abs(rep['recall']-official['recall']),'overall_rel':abs(rep['overall']-official['overall'])/official['overall'],'d2s_rel':abs(rep['mean_d2s']-official['mean_d2s'])/official['mean_d2s'],'s2d_rel':abs(rep['mean_s2d']-official['mean_s2d'])/official['mean_s2d']}
repro={'status':'PASS' if errs['f1_abs']<=1e-4 and errs['precision_abs']<=1e-4 and errs['recall_abs']<=1e-4 and max(errs['overall_rel'],errs['d2s_rel'],errs['s2d_rel'])<=1e-3 else 'FAIL_OFFICIAL_METRIC_REPRODUCTION','official':official,'recomputed_from_official_intermediate':rep,'errors':errs,'intermediate_path':str(meshdir/'vis_scene_01_data_down_stl.ply'),'validation_method':'independent sklearn nearest-neighbor recomputation from evaluator-emitted red/green point sets'}
(ROOT/'reports/stage06_r3_official_reproduction.json').write_text(json.dumps(repro,indent=2)+'\n')
trace=f'''# Stage 0.6-R3 official evaluator trace\n\n- Actual prediction: `{pred}`; loaded by `open3d.io.read_triangle_mesh` at `eval.py:51`; mesh-mode sampling at lines 53-76.\n- Actual GT: `{gt}`; full OBJ triangle mesh loaded by `open3d.io.read_triangle_mesh` at lines 111-116. No material filter; `Material.011` is **not** selected. Missing texture warnings do not remove geometry.\n- Prediction transform: COLMAP `(x,y,z)` to Blender `(x,z,-y)`, `eval.py:102-108`. GT transform: none. Normalization: none.\n- Crop: height-only `y > -0.1` on both sampled point sets, lines 119-127. Observation mask: none. Camera-frustum filter: none. BBox filter: none.\n- Connected-component cleaning: none inside evaluator. Input filename is already renderer post-processing output; renderer keeps the five largest triangle clusters (`render.py` post-process call).\n- Prediction sampling/downsample: deterministic triangle lattice from `sample_single_tri`, lines 11-20 and 58-76; radius de-duplication at 0.002 using sklearn KD tree, lines 84-99. Its shuffle uses unseeded `default_rng()` at line 86.\n- GT sampling: Open3D uniform surface sampling of 1,000,000 points, lines 113-117. No cache is read. The evaluator writes `vis_scene_01_data_down_stl.ply` at lines 130-142; R3 uses it only to independently reproduce the exact realized run.\n- Nearest-neighbor backend: `sklearn.neighbors.NearestNeighbors(algorithm="kd_tree", n_jobs=-1)`, lines 91, 145-157.\n- d2s = mean prediction-to-GT NN distance among distances `< max_dist=20`; s2d is reverse; overall=(d2s+s2d)/2, lines 145-157 and 196.\n- Precision/recall use strict distance `< visualize_threshold/2000 = 10/2000 = 0.005`; F1 is harmonic mean, lines 159-173.\n- Reported d2s/s2d/overall multiply raw world-unit means by 1000, lines 197 and 203-205. F1 threshold remains raw 0.005 world units. Distances >=20 are excluded from means but remain failures in precision/recall.\n- Local imports: none beyond NumPy, Open3D, sklearn, tqdm, scipy.io and multiprocessing (`eval.py:2-9`); no other local evaluation module participates.\n'''
(ROOT/'reports/stage06_r3_official_evaluator_trace.md').write_text(trace)
audit={'prediction':mesh_info(pred),'gt':mesh_info(gt),'gt_type':'triangle_mesh_obj','gt_material_filter':None,'uses_material_011':False,'cache_or_intermediate_read':False,'mode':'mesh','evaluator_code':str((ROOT/'third_party/TSGS/scripts/eval_translab/eval.py').resolve()),'distance_input_unit':'world units','reported_distance_multiplier':1000,'f1_threshold_world_units':.005,'mean_distance_truncation':20.0,'reproduction_status':repro['status']}
(ROOT/'reports/stage06_r3_actual_inputs.json').write_text(json.dumps(audit,indent=2)+'\n')
print(json.dumps({'reproduction':repro,'inputs':audit},indent=2))
raise SystemExit(0 if repro['status']=='PASS' else 2)
